### ISSUE TITLE
more features (fav, comments, follow, join group)

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#11] opened 2017-06-27 18:59 UTC
I hope you can add more features to do all popular things in steamcommunity like:

- favorite/unfavorite screenshots
- comment profiles
- follow/unfollow person
- join/leave steam group

It would be great if you could do it in the future updates ;)
Greetings

**Comment by SamerAlsayegh** [comment] 2017-07-06 01:08
I have added some functions for communities, and a new example for following using the bot accounts. [Check this example for more information:](https://github.com/Undeadkillz/node-steam-bot-manager/blob/master/examples/FollowBot.js)

If you want to explore the new community functions, please check [this file](https://github.com/Undeadkillz/node-steam-bot-manager/blob/master/classes/Community.js)

Please note, only the follow and unfollow have been tested, the others may work, or may need slight adjustments to function correctly.

**Comment by nvmego** [comment] 2017-07-06 09:07
Thank you very much for your work.

follow/unfollow person works great - tested. 
join/leave grup works great - tested.
previewSharedFile works great - tested.

I have only problem with favouriteSharedFile.
I copied votebot.js and changed in 'var upVote = function' from 'Community.upvoteSharedFile' to 'favouriteSharedFile' and getting error:

`C:\Users\CCC\Downloads\node-steam-bot-manager-master\2\node_modules\node-steam-bot-manager\classes\Community.js:103
        if (response.statusCode == 200 && JSON.parse(body).success == 1)
                    ^

TypeError: Cannot read property 'statusCode' of undefined
    at C:\Users\CCC\Downloads\node-steam-bot-manager-master\2\node_modules\node-steam-bot-manager\classes\Community.js:103:21
    at SteamCommunity._checkCommunityError (C:\Users\CCC\Downloads\node-steam-bot-manager-master\2\node_modules\steamcommunity\components\http.js:123:3)
    at Request._callback (C:\Users\CCC\Downloads\node-steam-bot-manager-master\2\node_modules\steamcommunity\components\http.js:51:88)
    at Request.self.callback (C:\Users\CCC\Downloads\node-steam-bot-manager-master\2\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Users\CCC\Downloads\node-steam-bot-manager-master\2\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Gunzip.<anonymous> (C:\Users\CCC\Downloads\node-steam-bot-manager-master\2\node_modules\request\request.js:1091:12)`

**Comment by nvmego** [comment] 2017-07-06 18:40
I have one more question: is it normal? doubled console log?

http://i.imgur.com/P7lpBXS.png

**Comment by SamerAlsayegh** [comment] 2017-07-06 19:00
The console issue is fixed in the latest commit, and as for the favourite/unfavourite it now works, and I have also provided an example of it.

**Comment by nvmego** [comment] 2017-07-06 19:06
I will test it in ~30 min, but I have question: can I remove completely 'docs' folder? without problem?

**Comment by SamerAlsayegh** [comment] 2017-07-06 19:11
Yeah, you can remove the folder. It's just in the repo, so that you can browse [the docs here. ](http://undeadkillz.github.io/node-steam-bot-manager/docs/)

**Comment by nvmego** [comment] 2017-07-06 19:40
I can confirm, double console log fixed, and favourite feature works great.
Thank you for your time and work.

**Comment by egoSB** [comment] 2017-07-09 18:34
I have question about last undone feature: comments.
We have spoken on Steam chat, but I can't handle with it, so I leaving it in your hands :D 

I tried to do script for comments with java array, works in half way, because script grabbing random string and posting same text with all linked accounts.
I want to do different comments for all the bots.

```
var BotManager = require('node-steam-bot-manager');
var botsManager = new BotManager();
var SteamProfile = '';

var array = [
"test 1",
"test 2",
"test 3",
];

var randomNumber = Math.floor(Math.random()*array.length);

function commentBot() {

    var comment = function () {

        for (var botAccountIndex in botsManager.getAccounts()) {

            (function () {
                var botAccount = botsManager.getAccounts()[botAccountIndex];

			botAccount.community.postUserComment(SteamProfile, array[randomNumber], function (err) {
                    if (err)
                        botsManager.errorDebug("Comment has not been sent with " + botAccount.getAccountName());
                    else
                        botsManager.infoDebug("Comment sent successfully with " + botAccount.getAccountName());
                });
            })();
        }
    };

    botsManager.startManager(function (err) {
        setTimeout(comment, 5000);
    });

}

new commentBot();

module.exports = commentBot;
```

**Comment by SamerAlsayegh** [comment] 2017-07-09 21:03
As I said, I may not code the approach, however, I am telling you how it can be done:


1. **Blacklist method** (for random comment from a list):
    Create a new arraylist by doing 'var indexBlacklist = [];'
when you post a comment just do  'indexBlacklist.push(INDEX);'
when you choose a comment, just do a while loop  with'(indexBlacklist.indexOf(INDEX) != -1)' and inside just set INDEX to a new random number. After the while loop just post the comment at 'array[INDEX]'

2. **The Index Method**:
    Every time you post a comment, just increase a variable called index by 1, so that the next time you choose a comment from array 'array', you get the next in the list. But make sure to check and ensure that index is never larger than the size of the list.

I am trying to guide you on how to do it, but I will not do it for you. This can help you learn, instead of just copying/pasting my codes blindly.

**Comment by egoSB** [comment] 2017-07-10 14:30
Thank you very much for advices, I will take look at it at weekend. 👍 

I have question about random delay at joining to group.
All accounts connecting after script start with autologin - it's OK, but how can I set random delay between join to group with every account.

` setTimeout(join, 1000 * 10)` works with all accounts, but how can I do random delay like `(Math.floor((Math.random() * 60) * 1000)`  with every linked accounts, like random delay between 0 - 60 sec.

I don't want to send all requests after 10 sec after script start. I want to do random delay between 0-60 sec with all accounts.

**Comment by SamerAlsayegh** [comment] 2017-07-10 15:35
You will need to set this timeout wrapping the part where the function(){/*CODE FOR JOINING GROUP HERE*/}() instead of around the for loop for accounts.

**Comment by egoSB** [comment] 2017-07-10 17:05
like that?

```
setTimeout(function JoinBot() {

    /**
     * We will join the group
     */
    var join = function () {
        /**
         * We will loop through all bot accounts
         */
        for (var botAccountIndex in botsManager.getAccounts()) {
            /**
             * To avoid over-writing the same variable due to the for loop, we will enclose in a function.
             */
            (function () {
                var botAccount = botsManager.getAccounts()[botAccountIndex];// Get botAccount from the index


                botAccount.Community.setupProfile(function(err){
                    if (err){
                        botsManager.errorDebug("Failed to set-up account. Due to " + err);
                    }
                    else {
                        /**
                         * We will execute the command to join group
                         */
                        botAccount.Community.joinGroup(groupID, function (err) {
                            if (err)
                                botsManager.errorDebug("Failed to join group." + err);
                            else
                                botsManager.infoDebug("Successfully joined group with " + botAccount.getAccountName());
                        });
                    }
                })

            })();
        }
};


    botsManager.startManager(function (err) {
        setTimeout(join, 10000);// We will delay 10 seconds until all accounts are expected to be logged in... There is obviously a much better way, however it requires a lot of code | This is just a simple example.
    });// You must start the manager at the end so that all the hooks above it, are registered.

}, Math.floor((Math.random() * 60) * 1000));
```

if yes, I getting `ReferenceError: JoinBot is not defined`

if I set `setTimeout(JoinBot, 3000);`, I don't see table with accounts in console (for 3 sec), and accounts isn't logging(for that 3 sec), and they sending all requests after 10 sec in the same time.

**Comment by SamerAlsayegh** [comment] 2017-07-10 22:03
No, it should look something similar to this... https://pastebin.com/dtNQhWWf
However, Idk if that code will work, as I don't have the bot running on my current laptop.

**Comment by egoSB** [comment] 2017-07-11 15:12
with this code looks like only 1 account trying to join (and actually joining to group) but looks like rest console logs are from that 1st acc 

`(Move up and down to reveal more choices)info: Successfully joined group with  xxxx
error: Failed to join group. Error: You are already a member of this group.
error: Failed to join group. Error: You are already a member of this group.
error: Failed to join group. Error: You are already a member of this group.
error: Failed to join group. Error: You are already a member of this group.
error: Failed to join group. Error: You are already a member of this group.
error: Failed to join group. Error: You are already a member of this group.
error: Failed to join group. Error: You are already a member of this group.
`

I created new group, with 0 members, and rest console logs showing you are already member of this group, when in group are 2 people.

**Comment by SamerAlsayegh** [comment] 2017-07-11 21:16
Try surround the setTimeout around the function(){.....}(); part of the code. Right now it is inside it, makr it surround it. That should in theory work, however I am unable to test rn.

**Comment by egoSB** [comment] 2017-07-12 16:02
Works! Thank you! ;)

**Comment by egoSB** [comment] 2017-07-22 12:45
Works! Thank you! ;)

You can close issue :)

**Closed as completed** 2017-07-22 13:30 UTC
Labels: enhancement
